### ISSUE TITLE
antlr-python-runtime 4.8

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pyquil-feedstock#40]
Just dug this feedstock up from a [search](https://github.com/search?q=org%3Aconda-forge+antlr-python-runtime&type=Code), but heads up that `antlr-python-runtime 4.8` is [ready to drop](https://github.com/conda-forge/antlr-python-runtime-feedstock/pull/4) and very possibly could break this package if the upstream is including code compiled from grammars with the `4.7` line. Please reply on that PR if you need me to wait to release it!

**Comment by karalekas** [comment]
@bollwyvl Hey! Thanks for the heads up -- how do I check if am including code compiled from grammars with the `4.7` line? And how do I upgrade them in that case?

**Comment by bollwyvl** [comment]
If you look through the upstream source, you might find some .py that says
"created with antlr 4.7" or something. Unless they also require Java and
actual antlr4 to run, this is likely.

If that is the case, you'll probably want to put a top pin on the version
(e.g. python-antlr-runtime >=4.7,<4.8) as it's unknown whether they will
work. Anecdotally, Python generated by 4.7 did not work with older runtimes.

**Comment by karalekas** [comment]
Ok, I see `# Generated from Quil.g4 by ANTLR 4.7.2` in a couple files. So the recommended solution is to essentially pin the package version?

**Comment by bollwyvl** [comment]
Yeah, probably  >=4.7.2,<4.8 to be safe.

**Comment by karalekas** [comment]
great will do, thanks!

**Comment by karalekas** [comment]
This should be resolved in the upcoming `v2.17.0` release of pyquil, thanks @bollwyvl !
